### ISSUE TITLE
Split the book in several files

### ISSUE THREAD

**Issue by ngryman** [sarisboo/the-practical-handbook-to-world-remedies#1]
In order for Leanpub to work correctly you will need to split your monolith file into several ones, where each one is a chapter.

I would advise you to create one file per chapter and name that file `chapter{#}.md` where `{#}` is the chapter number. In order for the file to be sorted alphabetically you would need to zerofill your chapter number for the 9 first (ie. `chapter01.md`, `chapter02.md`, ...).

Then you would need to create a `book.txt` that lists all the chapter files.

Here is an [example](https://github.com/genomicsclass/leanpub) of a Leanpub book which is funnily about data science 😃 

### TODO
- [ ] Create a `manuscript` directory.
- [ ] Split in several files.
- [ ] Create a `book.txt` file.
